# Generated by Django 3.0.14 on 2021-05-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_display_name_as_mandatory'),
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravatoken',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strava_tokens', to='challenges.ExternalProfile'),
        ),
    ]
