# Generated by Django 3.0.7 on 2021-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
