# Generated by Django 3.0.12 on 2021-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_stats_calories_default_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='endomondo_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='endomondo_id',
            new_name='external_id',
        ),
    ]
