trigger:
  branches:
    exclude:
      - releases/master

jobs:
  - job: Stage
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-18.04"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
          architecture: "x64"
      - bash: |
          set -e
          cd endomondo_app
          pip3 install -r requirements.txt
          export PYTHONPATH=$(pwd)
          python3 manage.py test
        displayName: "Test"
