version: '3'

services:
  app:
    build: .
    command: ["/app_entrypoint.sh"]
    volumes:
      - ./project/db:/app/project/db
      - ./project/logs:/app/project/logs
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
  cron:
    build: .
    command: ["/cron_entrypoint.sh"]
    volumes:
        - ./project/db:/app/project/db
        - ./project/logs:/app/project/logs
    restart: always
    env_file:
        - .env
