version: '3'

services:
  app:
    build: .
    command: ["/app_entrypoint.sh"]
    volumes:
      - ./core/db:/app/core/db
      - ./core/logs:/app/core/logs
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
  cron:
    build: .
    command: ["/cron_entrypoint.sh"]
    volumes:
        - ./core/db:/app/core/db
        - ./core/logs:/app/core/logs
    restart: always
    env_file:
        - .env
