# Generated by Django 3.0.3 on 2020-02-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('challange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challange.Challange')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(to='challange.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.IntegerField()),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challange.Challange')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challange.Competitor')),
            ],
        ),
    ]
