# Generated by Django 3.0.14 on 2021-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_add_related_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='calories',
            new_name='value',
        ),
        migrations.AddField(
            model_name='challenge',
            name='kind',
            field=models.CharField(choices=[('ENDOMONDO', 'Endomondo'), ('STRAVA', 'Strava')], default='ENDOMONDO', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='external_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='external_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='kind',
            field=models.CharField(choices=[('SPORT', 'Sport'), ('WALK', 'Walk'), ('RUN', 'Run'), ('SWIM', 'Swim'), ('BIKE', 'Bike'), ('HIKE', 'Hike')], default='SPORT', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='unit',
            field=models.CharField(choices=[('CALORIES', 'Calories'), ('KILOMETERS', 'Kilometers')], default='CALORIES', max_length=16),
            preserve_default=False,
        ),
    ]
