# Generated by Django 3.0.14 on 2021-05-06 23:10

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Competitor = apps.get_model("challenges", "Competitor")
    ExternalProfile = apps.get_model("challenges", "ExternalProfile")

    for comp in Competitor.objects.all():
        ExternalProfile.objects.create(competitor=comp, external_id=comp.external_id, name=comp.name, kind='ENDOMONDO')


def reverse_func(apps, schema_editor):
    ExternalProfile = apps.get_model("challenges", "ExternalProfile")

    ExternalProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_extend_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENDOMONDO', 'Endomondo'), ('STRAVA', 'Strava')], max_length=16)),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_profiles', to='challenges.Competitor')),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
