# Generated by Django 3.0.14 on 2021-05-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_add_external_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='name',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
