# Generated by Django 3.0.14 on 2021-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_remove_fields_from_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
