# Generated by Django 3.0.14 on 2021-05-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_display_name_as_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='unit',
            field=models.CharField(choices=[('CALORIES', 'Calories'), ('METERS', 'Meters')], max_length=16),
        ),
    ]
